### ISSUE TITLE
«Настройки редактора»

### ISSUE THREAD

**Issue by Takohashi** [ilyahoilik/invision.system.ru#100]
Ключ: **menu__core_editor_toolbar**
«Toolbars» переведено как «Настройки редактора», что создаёт путаницу в меню:

![2018-03-05 23 20 19](https://user-images.githubusercontent.com/9580166/36998418-ed667342-20cd-11e8-8f6c-19ddb44664a1.png)

Оригинал:

![2018-03-05 23 20 01](https://user-images.githubusercontent.com/9580166/36998434-fa5a7030-20cd-11e8-94ef-c49e720c761e.png)

Должно быть «Панели инструментов» или «Тулбары».

**Comment by ilyahoilik** [comment]
Пока они не добавили новый пункт "Настройки" там все было нормально :) Посмотрю потом как назвать так, чтобы влезало в одну строку.

**Comment by Takohashi** [comment]
«Панели инструментов» влезает, я специально предварительно проверил. Хотя можно и в единственном числе — привычней на слух.
