### ISSUE TITLE
Пунктуация в сообщении о нарушении

### ISSUE THREAD

**Issue by chimit** [ilyahoilik/invision.system.ru#102]
В процессе фикса проблемы с потерявшимся пробелом (https://github.com/ilyahoilik/invision.system.ru/pull/101) обнаружил две странности в самом IPS:

После "Выданы баллы" стоит двоеточие, а после "Премодерация" - дефис. Наверно лучше привести это к единому формату. Но, очевидно, это в самом движке. Да, и дефис вообще правильнее было бы заменить на тире во всех подобных случаях, т.к. по сути это пунктуационная ошибка.

![2018-03-13 11 51 53](https://user-images.githubusercontent.com/839349/37322054-5d00186e-26b6-11e8-86d1-555da5096ca8.png)

Вторая проблема в том, что после однородных сообщений где-то есть точка на конце, а где-то ее нет:

![2018-03-13 11 56 05](https://user-images.githubusercontent.com/839349/37322092-9047c780-26b6-11e8-9ab5-b5b4693def03.png)

**Comment by ilyahoilik** [comment]
Наверное это все же лучше в IPS писать, чтобы они это централизованно приводили в порядок. Из PR я изменения взял, в следующую версию они будут внесены.
