### ISSUE TITLE
Настройка репутации 

### ISSUE THREAD

**Issue by Sipsb** [ilyahoilik/invision.system.ru#110]
Ключ: **rep_settings_blurb**

Система репутации позволяет пользователям зарабатывать **баллы репутации** когда другие пользователи реагируют на его публикации. Общая репутация пользователя отображается рядом с его публикациями и в его профиле, **наряду** с счётчиками в блоке "Популярные авторы" и Таблице лидеров.

Заменить: после "баллы репутации" **запятая** и наряду --> **рядом**

**Comment by Takohashi** [comment]
с счётчиками → со счётчиками, на его → на их. Да и сам блок в переводе называется «Лучшие авторы», а не «Популярные авторы».

А вообще, странный какой-то перевод предложили. Там и так неправильно переведено, так ещё и «рядом» зачем-то два раза писать хотите.

Мой вариант:
Система репутации позволяет пользователям получать баллы репутации, когда другие пользователи реагируют на их публикации. Репутация пользователей отображается рядом с их публикациями и в их профилях, а также учитывается в таких функциях, как блок «Лучшие авторы» и Таблица лидеров.
