### ISSUE TITLE
Информационная строка под названием темы

### ISSUE THREAD

**Issue by Takohashi** [ilyahoilik/invision.system.ru#113]
Вероятно, она генерируется из нескольких ключей, поэтому не буду их называть, чтобы не ошибиться.

Я имею в виду эту строку:
Табличный вид:
![2018-05-10 12 21 04](https://user-images.githubusercontent.com/9580166/39862818-830b0806-544d-11e8-9a67-372398a46880.png)
Динамический вид:
![2018-05-10 12 20 03](https://user-images.githubusercontent.com/9580166/39862829-8b2f5492-544d-11e8-9a97-da9a76ae8278.png)
На странице самой темы:
![2018-05-10 12 20 27](https://user-images.githubusercontent.com/9580166/39862843-94ddead0-544d-11e8-9f21-52fd2f83b9d6.png)

В оригинале это по сути читабельное предложение, а в переводе больше напоминает набор слов.
1. Нужно убрать запятую в дате между днём и годом. В штатовском формате даты день стоит после месяца, поэтому там запятая отделяет два числа (день и год), в нашем формате даты там запятая не используется и не нужна.
2. Насчёт названия разделов в конце. В английском нет изменений формы слова по падежам, да и все слова в заголовках они пишут с большой буквы, поэтому в оригинальной локализации всё выглядит и читается корректно. А в русской локализации получается что-то в духе **в Общеигровой раздел**, или **в Музыка**, или **в Книги и журналы** — в общем, выглядит очень странно. Само собой окончания никак не поменять, предлагать добавить слово «раздел» (**в разделе Музыка**, **в разделе Книги и журналы**) тоже не буду, но может хотя бы названия в кавычки взять, чтобы хотя бы так немного улучшить читаемость и внешний вид — **в «Музыка»**, **в «Книги и журналы»**

Второй пункт не обязательный (а просто желательный), но вот запятую из даты надо убрать.

**Comment by ilyahoilik** [comment]
Второй пункт я бы с радостью сделал, но там не очень удачно строка формируется - по частям в самом шаблоне. Через языковую систему проходит только `Автор: xxx,` и `в`. Ну и дата ещё, но у неё свои заморочки. Поэтому добавить `в разделе` или кавычки не получится. А запятую убрал.
