### ISSUE TITLE
mailsub__core_notification_new_status

### ISSUE THREAD

**Issue by GitKira** [ilyahoilik/invision.system.ru#117]
Ключ mailsub__core_notification_new_status
Оригинал {$comment->author()->name|raw} has posted a new status
Перевод {$comment->author()->name|raw} оставил новой сообщение в ленте

Наверное, надо "новое" :)

**Comment by Takohashi** [comment]
Мм, только у меня, глядя на оригинал и перевод, возник вопрос — откуда взялось «в ленте» и почему «статус» превратился в «сообщение»?

**Comment by GitKira** [comment]
Я мельком просмотрел похожие строки, увидел несколько подобных метаморфоз и посчитал, что это адаптация.

**Comment by ilyahoilik** [comment]
Там всё нужно переделывать, да. Судя по всему, ещё на стадии разработки перевода всё превратилось в кашу. Надо будет поправить, займусь этим для 4.3.3.
