### ISSUE TITLE
Уведомления

### ISSUE THREAD

**Issue by GitKira** [ilyahoilik/invision.system.ru#118]
Ключ - что-то внутри notification__new_comment или другие с ключом, содержащим "notification", либо переменные. Не смог найти через админку.

Проблема - если уведомление содержит более одного имени пользователя, они помещаются друг за другом без пробелов.

Оригинальные сообщения
User1 and User2 commented on Topic
User1, User2 and User3 commented on Topic
User1, User2, User3 and 1 other commented on Topic
User1, User2, User3 and 42 others commented on Topic

Переведённое
User1User2 оставили комментарии в Topic
User1User2User3 оставили комментарии в Topic
User1User2User31 другой оставили комментарии в Тема
User1User2User342 других оставили комментарии в Тема

**Comment by ilyahoilik** [comment]
Какой у вас указан перевод строки `_list_format_`? Вы его случаем не меняли? У меня сейчас уведомление висит с двумя пользователями (правда не о новой теме, а о реакциях), там всё в порядке.

**Comment by GitKira** [comment]
"a, b и c"

**Comment by ilyahoilik** [comment]
Даже не знаю чем помочь. У меня вот так всё выглядит
<img width="437" alt="2018-05-18 4 04 31" src="https://user-images.githubusercontent.com/7265704/40210993-a5f0bcea-5a50-11e8-9773-8241d23818a5.png">

Попробуйте из этой строки полностью удалить перевод и посмотреть, исправится ли проблема.

**Comment by GitKira** [comment]
Убрал, проверил - исправилось
Ввёл ручками - исправилось и перевелось
Откатил изменения (Ctrl+Z), сверил ввод - совпало. 
Сохранил то, что откатил - проблема исчезла.
Фантастика о_О

**Comment by ilyahoilik** [comment]
Вот так вот и работаем. Было исправлено, но непонятно что и каким образом :)
