### ISSUE TITLE
Текст не помещается в кнопку

### ISSUE THREAD

**Issue by GitKira** [ilyahoilik/invision.system.ru#119]
Ключи reply_and_ (поддержка)

Проблема - не влазят локализованные ответы

Перевод
![image](https://user-images.githubusercontent.com/10116101/40210759-7e53e10e-5a4f-11e8-874f-a30ee91060dc.png)

Оригинал
![image](https://user-images.githubusercontent.com/10116101/40210783-9d88a9c4-5a4f-11e8-8aa2-b879c6edfc70.png)

**Comment by ilyahoilik** [comment]
Есть идеи? Я видел это ещё при переводе и не смог сделать перевод ещё короче. Разве что писать разработчикам, чтобы что-то сделали с кнопками.

**Comment by GitKira** [comment]
Ответить и остаться
Ответить и к следующему
Ответить и к списку

Или "ответить" в выпадающем списке на "Отв."
Все варианты выглядят кривовато, но 
1. это "админский" интерфейс
2. так лучше, чем обрезанная строка :)
