### ISSUE TITLE
Незамедлительно при указании времени публикации

### ISSUE THREAD

**Issue by TemKaSD** [ilyahoilik/invision.system.ru#121]
Нужно перефразировать, например, на: Текущая дата и время.
![screenshot_1](https://user-images.githubusercontent.com/6318282/40300380-711dc772-5d2c-11e8-833a-08cfbbdad312.png)

**Comment by ilyahoilik** [comment]
Не вижу в этом необходимости

**Comment by TemKaSD** [comment]
@ilyahoilik Вы ведь делаете для людей, для себя вы может и не видите, для многих логика этой фразы будет не понятно. Данная фраза подразумевает указать дату публикации текущей, а не опубликовать запись незамедлительно.

**Comment by Takohashi** [comment]
@TemKaSD Там выбор из двух вариантов. Первый — с указанием времени, то есть отсрочка публикации после сохранения. Второй — без указания времени, то есть незамедлительная публикация.
«Незамедлительно — Без задержек; немедленно.» Толковый словарь Ефремовой

**Comment by TemKaSD** [comment]
Вы меня не понимаете. Замените на "Текущая дата и время" и будет вам счастье.

**Comment by ilyahoilik** [comment]
В оригинале строка называется 'Immediately', и она используется в разных областях сайта. Не вижу ни единой причины, по которой нужно менять смысл оригинальной строки.
