### ISSUE TITLE
Косяк в файле Translate Russian Pack для версии 4.2

### ISSUE THREAD

**Issue by sovushik** [ilyahoilik/invision.system.ru#13]
После установки языкового пакета вот так стала отображаться лента активности - без маленьких аватарок
![img_7643 png 1aa89f7df03d5375150c8a9d4b96973b](https://user-images.githubusercontent.com/30425777/28554270-049cd04a-7112-11e7-90bb-3623222503e1.PNG)

Я отписал в Client Area IPS'ов и они решили проблему, при этом написали, что дело в кривом переводе!
Прикладываю их ответ, уверен, он будет полезным!
Спасибо!

I have investigated this issue and it appears to be a problem with your language pack. I have resolved this issue for you, however if you are using a marketplace language pack you may want to reach out to the mod author and let them know of this issue.The specific string that was incorrect was "activity_member_reacted".

Regards,

Jennifer M
Invision Power Services Inc

**Comment by ilyahoilik** [comment]
Это баг в системе. При скачивании языкового пакета он сам конвертирует необходимый тег в ссылку сайта, с которого языковой пакет скачан. Я попробую исправить это через html-мнемонику.
