### ISSUE TITLE
Новые публикации в ленте активности

### ISSUE THREAD

**Issue by Takohashi** [ilyahoilik/invision.system.ru#134]
**Ключ**: newActivityItems

Оригинал:
`There {!# [1:is a new item][?:are # new items]} to view. Click here to load {!# [1:it][?:them]}.`

Текущий перевод:
`{!# [0:Появилось # новых элементов][1:Появился новый элемент][2:Появилось # новых элемента][3:Появилось # новых элемента][4:Появилось # новых элемента][11:Появилось # новых элементов][12:Появилось # новых элементов][13:Появилось # новых элементов][14:Появилось # новых элементов][*1:Появилось # новый элемент][*2:Появилось # новых элемента][*3:Появилось # новых элемента][*4:Появилось # новых элемента][?:Появилось # новых элементов]}. Нажмите здесь для {!# [1:его][*11:Появилось # новых элементов][*12:Появилось # новых элементов][*13:Появилось # новых элементов][*14:Появилось # новых элементов][?:их]} загрузки и просмотра.`

Обратил внимание, что неправильно пишется при наличии одного элемента:

![2018-06-30 13 52 02](https://user-images.githubusercontent.com/9580166/42125828-bfda6f86-7c86-11e8-9ac8-53f218587290.png)

Но посмотрел на перевод и там оказались и другие ошибки:
1. **Это важно!** Конструкции вида `[*1: ...], [*2: ...]` и тд включают в себя `[1: ...], [2: ...]` и начинают их перекрывать, если указаны в конце, поэтому все конструкции со "`*`" должны быть указаны в самом начале.
2. С учётом пункта №1 нет смысла указывать `[2:Появилось # новых элемента]` при наличии `[*2:Появилось # новых элемента]` и тп.
3. Во втором предложении указаны лишние конструкции для 11, 12, 13, 14:
![2018-06-30 15 06 36](https://user-images.githubusercontent.com/9580166/42125836-d1a2bdae-7c86-11e8-951b-4815d87ccabe.png)
4. Не могу понять, какой смысл в конструкции `[0:Появилось # новых элементов]`? Без неё всё работает. Обратил внимание, что и в других местах локализации тоже есть конструкции для «0», хотя в оригинале этого нет.

Предлагаю такой перевод (проверил, работает правильно):
`{!# [*1:Появился # новый элемент][*2:Появилось # новых элемента][*3:Появилось # новых элемента][*4:Появилось # новых элемента][1:Появился новый элемент][11:Появилось # новых элементов][12:Появилось # новых элементов][13:Появилось # новых элементов][14:Появилось # новых элементов][?:Появилось # новых элементов]}. Нажмите здесь для {!# [1:его][?:их]} загрузки и просмотра.`

PS. Если пункт №1 не соблюдён в других аналогичных местах локализации, то там тоже будут выводиться не те конструкции из-за неправильного перекрытия.

**Comment by ilyahoilik** [comment]
Всегда было наоборот, у первых вариантов был наивысший приоритет. Буду тестировать
