### ISSUE TITLE
Не отображаются названия категорий смайликов

### ISSUE THREAD

**Issue by ilyahoilik** [ilyahoilik/invision.system.ru#150]
Что-то я у себя с последним обновлением переведённых названий в редакторе не вижу... Хотя в админке в языках перевод присутствует.

_Originally posted by @Takohashi in https://github.com/ilyahoilik/invision.system.ru/pull/135#issuecomment-459940448_

**Comment by Takohashi** [comment]
После обновления до 4.4.0 перевод появился.

**Comment by ilyahoilik** [comment]
Ага, спасибо за информацию
