### ISSUE TITLE
Галерея - Отсутствует ключ

### ISSUE THREAD

**Issue by Sipsb** [ilyahoilik/invision.system.ru#151]
Отсутствует ключ: **sitemap_gallery_Images** 
При перестроение карты сайта не отображается название.
![2019-02-16_07-24-41](https://user-images.githubusercontent.com/22107941/52894583-db0a2a80-31bc-11e9-847c-a5dc789d7860.png)

**Comment by ilyahoilik** [comment]
<img width="521" alt="Снимок экрана 2019-03-09 в 1 41 39" src="https://user-images.githubusercontent.com/7265704/54060135-a3672f00-420c-11e9-960f-b756dcada1b1.png">
