### ISSUE TITLE
"Уведомлять меня, когда другие пользователи отправляют комментарии"

### ISSUE THREAD

**Issue by chimit** [ilyahoilik/invision.system.ru#153]
Предлагаю укоротить данную строчку из блога по аналогии с такой же строчкой в форуме: "Сообщать о новых комментариях".

![image](https://user-images.githubusercontent.com/839349/53153855-46586000-35f4-11e9-8d78-4d95d5f36508.png)

![image](https://user-images.githubusercontent.com/839349/53153871-4eb09b00-35f4-11e9-9fbd-fc0a48f932a6.png)

Ну и на кнопке тоже какое-то расхождение стилей: "Добавить комментарий" и "Отправить ответ".

**Comment by ilyahoilik** [comment]
Всё верно, так как в блоге - комментарии, а на форуме - сообщения/ответы.
Длинную фразу я поправил, там переизбыток перевода был:
>Уведомлять меня при публикации других комментариев

**Comment by chimit** [comment]
Я имею ввиду, что функцию однотипные, а лексика используется разная. Ощущение, будто переводили два разных человека (вероятно, так и было).

Мой вариант:
1. Для форума: 
    - _Уведомлять о новых ответах_
    - _Добавить ответ_
2) Для блога: 
    - _Уведомлять о новых комментариях_
    - _Добавить комментарий_

**Comment by ilyahoilik** [comment]
В следующий релиз пойдёт
