### ISSUE TITLE
Предложения по переводу

### ISSUE THREAD

**Issue by rokii666** [ilyahoilik/invision.system.ru#156]
Здравствуйте! Я бы предложил более лаконичные варианты для меню, поскольку оно слишком растягивается при текущем варианте. 

Например, заменить:

Наша команда - Администрация
Пользователи в сети - В сети - Онлайн (что пользователи будет ясно и так, потому что вкладка Сообщество)
Таблица лидеров - Лидеры (что таблица будет и так ясно)

**Comment by Takohashi** [comment]
1. По поводу «Нашей команды» уже было в своё время обсуждение и остановились именно на этом варианте. Модераторы, которые отображаются в том списке, администрацией не являются.
2. Не знаю, зачем в принципе добавлять этот пункт в меню, когда онлайн-юзеров можно отображать в виджете внизу страницы.
3. «Таблица лидеров» не сильно отличается по длине от оригинального названия. Просто «Лидеры» может вводить в заблуждение, что там отображается что-то схожее с «Нашей командой».

**Comment by white-miku** [comment]
1. Воздержусь. Ни за, ни против.
2. Против. Не у всех пункт "Пользователи в сети" может быть под вкладкой "Сообщество". В итоге может получится не очень.
3. Предложение не нравится. Я бы предложил что-то вроде "Лучшие". Хотя тут возникает вопрос "Лучшие... Кто? или Что?"

**Comment by rokii666** [comment]
> 1. По поводу «Нашей команды» уже было в своё время обсуждение и остановились именно на этом варианте. Модераторы, которые отображаются в том списке, администрацией не являются.

Я почему-то думал что модераторы - это тоже администрация. Я сам переименовал в Руководство у себя, потом начались в голове ассоциации с Руководством пользователя (наверное не у всех такое), переименовал обратно в Администрацию. Раньше на vBulletin был перевод Руководство форума.


> 2\. Не знаю, зачем в принципе добавлять этот пункт в меню, когда онлайн-юзеров можно отображать в виджете внизу страницы.

Логично. Но раз есть по умолчанию - то я бы сократил.

> 3\. «Таблица лидеров» не сильно отличается по длине от оригинального названия. Просто «Лидеры» может вводить в заблуждение, что там отображается что-то схожее с «Нашей командой».

Тогда добавление слова Таблица тут не помогает, смысла не добавляет такого, что отличило бы ее от Нашей команды, поскольку там тоже - таблица своего рода.

> 2\. Против. Не у всех пункт "Пользователи в сети" может быть под вкладкой "Сообщество". В итоге может получится не очень.

Тот же ответ - так по умолчанию, а значит у большинства. А у нас, как известно, демократия - власть большинства над меньшинством :)

> 3\. Предложение не нравится. Я бы предложил что-то вроде "Лучшие". Хотя тут возникает вопрос "Лучшие... Кто? или Что?"

Так как там все равно уже Таблица лидеров, то почему бы просто не убрать Таблица?

**Comment by white-miku** [comment]
@rokii666 
> Тот же ответ - так по умолчанию, а значит у большинства. А у нас, как известно, демократия - власть большинства над меньшинством :)

Не согласен. Текущий вариант универсален, а новый загоняет в рамки.

> Так как там все равно уже Таблица лидеров, то почему бы просто не убрать Таблица?

На мой взгляд сейчас слово "Таблица" в контексте "Таблица лидеров" создаёт ассоциация с некой таблицей результатов или рекордов (у нас же там ещё показывается и причина, по которой пользователь туда попал). Если же его убрать и оставить только что-то вроде "Лидеры", пропадает эта ассоциация.

В целом, по поводу всех этих изменений могу сказать вот что:
Ещё когда мы с Ильёй занимались переводом вместе, мы старались все надписи, подписи и прочее переводить максимально близко к оригиналу, за исключением тех случаев, когда текст получался слишком длинным и ломал разметку. Именно потому во многих областях IPS Community Suite существуют такие фразы, как "Отправить комментарий" вместо "Отправить пост" или же "Отправить сообщение", как это было когда-то в IP.Board 3.x. На мой взгляд такой перевод по-прежнему является наиболее универсальным.
_Всё вышесказанное является моим личным мнением._

**Comment by ilyahoilik** [comment]
Спасибо за предложения. Мы перевод меню пересматривали не раз и текущий вариант является оптимальным. Всем спасибо за высказанное мнение.
