### ISSUE TITLE
Не переведено

### ISSUE THREAD

**Issue by rokii666** [ilyahoilik/invision.system.ru#162]
Здравствуйте! 

В 4.4 есть места без перевода. Вот одно из них (то что выше в блоке - тоже я сам перевел). Это сообщение для гостей, которые могут вначале написать, а позже зарегистрироваться - новая функция:
<img width="853" alt="screen shot 2019-03-04 at 2 47 57 pm" src="https://user-images.githubusercontent.com/11616598/53734533-eb90f500-3e8c-11e9-9134-da9f6572fae0.png">

**Comment by ilyahoilik** [comment]
А вы перевод для 4.4 установили? Он только сегодня с утра вышел. там всё переведено

**Comment by rokii666** [comment]
Нет)
Вот тогда по горячим следам: Ьакунт
<img width="1035" alt="screen shot 2019-03-04 at 5 02 09 pm" src="https://user-images.githubusercontent.com/11616598/53741551-59deb300-3e9f-11e9-8fc7-cf978c00932e.png">

**Comment by ilyahoilik** [comment]
А об этом уже сообщили в #164 🙂
