### ISSUE TITLE
Коммерция - Отсутствует ключ

### ISSUE THREAD

**Issue by Sipsb** [ilyahoilik/invision.system.ru#163]
Отсутствует ключ: nexus_gateway_1_ins

![2019-03-04_17-25-58](https://user-images.githubusercontent.com/22107941/53739408-ba232400-3ea2-11e9-8cac-fb319492e639.png)

**Comment by ilyahoilik** [comment]
Там должен отображаться текст, который ты ввёл в настройках способа оплаты

**Comment by Sipsb** [comment]
Да, так и есть. По какой-то причине данное поле сохранилось без описания.
