### ISSUE TITLE
Перевод вводит в заблуждение

### ISSUE THREAD

**Issue by rokii666** [ilyahoilik/invision.system.ru#165]
В этом месте все пытался настроить, перестроить, не получалось, пока не дошло, что я не правильно понимаю первый пункт. Поскольку в последующих указано слово email, а в самом движке есть уведомления в меню, помимо email, я подумал что первый вариант - это уведомления в меню, а не по email. Возможно был бы лучше вариант вроде "Одно email-письмо при появлении новых публикаций"?

**Comment by rokii666** [comment]
Забыл скрин, вот
<img width="489" alt="screen shot 2019-03-05 at 5 02 29 pm" src="https://user-images.githubusercontent.com/11616598/53814785-ff118e00-3f68-11e9-99b8-2b3247007ef2.png">

**Comment by ilyahoilik** [comment]
Это в каком месте так, в смысле на что вы пытаетесь подписаться?

Первый параметр зависит от установленного способа уведомления в настройках уведомлений. Вот для примера скриншоты подписки на раздел форума при разных способах уведомления.

<img width="538" alt="2019-03-05 18 22 29" src="https://user-images.githubusercontent.com/7265704/53816150-202bac00-3f74-11e9-879a-cd61120f187d.png">
<img width="538" alt="2019-03-05 18 22 40" src="https://user-images.githubusercontent.com/7265704/53816153-20c44280-3f74-11e9-8f48-e40cf10cb6fc.png">
<img width="538" alt="2019-03-05 18 22 57" src="https://user-images.githubusercontent.com/7265704/53816158-20c44280-3f74-11e9-8438-dadf5f5bdf39.png">
<img width="538" alt="2019-03-05 18 25 52" src="https://user-images.githubusercontent.com/7265704/53816180-2b7ed780-3f74-11e9-8ca4-ac907f093c0c.png">


Как видите, пункт называется по-разному.

**Comment by ilyahoilik** [comment]
А, я увидел

**Comment by ilyahoilik** [comment]
Если там по первому пункту действительно идет уведомление по email, то это баг системы, а не перевода. Они не ту строку используют. Я посмотрю как приеду домой. Если подтвердится - напишу им.

follow_type_immediate
follow_type_immediate_email

**Comment by ilyahoilik** [comment]
А вы точно тот метод уведомления меняете? За ответы в теме отвечает строка «Кто-либо отвечает на публикацию, на которую я подписан» или как-то так, по памяти пишу.

**Comment by rokii666** [comment]
Разобрался. Я даже не замечал что там внизу еще куча настроек, оно настройку подсвечивает, но к ней не спускает.

**Comment by ilyahoilik** [comment]
Сообщил в IPS о возможно неправильно указанном языковом ключе

**Comment by ilyahoilik** [comment]
Им кажется, что всё правильно.
