### ISSUE TITLE
Ознакомление с предупреждением

### ISSUE THREAD

**Issue by rokii666** [ilyahoilik/invision.system.ru#166]
Вот скрин страницы после выдачи нарушения админом, там написано Вы ознакомились, но это обращение к пользователю, которому выдали нарушение, правильно было бы либо просто Ознакомился (двусмысленно), либо Пользователь ознакомился
<img width="593" alt="screen shot 2019-03-06 at 10 45 49 pm" src="https://user-images.githubusercontent.com/11616598/53912557-dcaf6b80-4061-11e9-9384-ee5fd91baf0e.png">

**Comment by TheAndrey** [comment]
Есть одна проблема. Это сообщение отображается как пользователю, так модератору. Я поэтому его не принимал за ошибку.
Теперь же пользователь будет видеть на своей стороне «Пользователь ознакомился». Думаю, стоит прийти к общему варианту: Ознакомлен / не ознакомлен.

**Comment by ilyahoilik** [comment]
@TheAndrey вы правы, спасибо
