### ISSUE TITLE
Описание ленивой загрузки

### ISSUE THREAD

**Issue by Takohashi** [ilyahoilik/invision.system.ru#168]
Ключ: lazy_load_enabled_desc
Оригинал:
«...This can improve page load times and reduce bandwidth.»
Текущий перевод:
«...Это может **увеличить время загрузки страницы** и уменьшить трафик.»

Должно быть — «улучшить время загрузки страницы». Или «сократить...»

**Comment by Takohashi** [comment]
И ещё в том же ключе — лучше не «пока пользователь **не прокручивает** страницу настолько, чтобы их увидеть», а «пока пользователь **не прокрутит** страницу настолько, чтобы их увидеть».

**Comment by ilyahoilik** [comment]
Мда, я точно помню, что мысленно проговаривал «улучшить». Думаю одно, а руки пишут другое :)
