### ISSUE TITLE
Дайджест - не переведено

### ISSUE THREAD

**Issue by rokii666** [ilyahoilik/invision.system.ru#169]
Добрый день!
Дайджест с форума приходит, тема не переведена, написано Your site.com digest

**Comment by ilyahoilik** [comment]
Можно скрин? Такой фразы нет вообще нигде в языковом пакете

**Comment by rokii666** [comment]
<img width="1112" alt="screen shot 2019-03-08 at 6 09 33 pm" src="https://user-images.githubusercontent.com/11616598/54040166-6891d680-41cd-11e9-8de0-76a1ff8a3402.png">

<img width="1105" alt="screen shot 2019-03-08 at 6 09 42 pm" src="https://user-images.githubusercontent.com/11616598/54040178-6fb8e480-41cd-11e9-8a42-2e558eb20fbf.png">

**Comment by ilyahoilik** [comment]
У вас в настройках аккаунта видимо включен английский язык. Все строки из этого письма переведены. Вот та, про которую вы говорили:
<img width="730" alt="2019-03-08 19 12 22" src="https://user-images.githubusercontent.com/7265704/54040389-43559600-41d6-11e9-9274-4435d445b33c.png">
