### ISSUE TITLE
Пожалуйста, убедитесь, ваша подпись соответствует со следующими правилам

### ISSUE THREAD

**Issue by varyen** [ilyahoilik/invision.system.ru#17]
Привет.

`<word key="ensure_signature_restrictions" js="0">Пожалуйста, убедитесь, ваша подпись соответствует со следующими правилам</word>`

Лучше "Пожалуйста, убедитесь что ваша подпись соответствует следующим правилам".

Спасибо за перевод и за то, что ловите багфиксы. :)

**Comment by ilyahoilik** [comment]
Вам спасибо за баг-репорты :)
