### ISSUE TITLE
Нет перевода 

### ISSUE THREAD

**Issue by Sipsb** [ilyahoilik/invision.system.ru#20]
**Spam Defense**  (Антиспам, Защита от спама)

**Comment by ilyahoilik** [comment]
Это название сервиса, то есть имя собственное. Поэтому я решил его не переводить. Подумаю, может переведу.

**Comment by ilyahoilik** [comment]
Имена собственные (SendGrid, Google Analytics или GeoIP Service) переводиться не будут.
