### ISSUE TITLE
Отказ от рассылок

### ISSUE THREAD

**Issue by Sipsb** [ilyahoilik/invision.system.ru#23]
Ключ: **unsubscribed_desc**

Предлагаю сделать (настройки уведомлений) выделенной ссылкой (http://site.ru/notifications/options/). 

Если пользователь случайно или намеренно нажал отписаться от рассылки и передумал! Он вероятней всего не сможет самостоятельно найти ссылку на отмену этих действий.

![2017-08-10 4 04 30](https://user-images.githubusercontent.com/22107941/29150134-291a0340-7d81-11e7-8e1a-c06b94c1e9c2.png)

**Comment by ilyahoilik** [comment]
Это нужно писать разработчикам, мы не можем просто так поместить ссылку, ибо на разных сайтах она может иметь разный вид (например, при выключенном FURL), а также просто быть изменена вручную.
