### ISSUE TITLE
Пропустить заолнение профиля

### ISSUE THREAD

**Issue by chimit** [ilyahoilik/invision.system.ru#24]
![2017-08-10 10 27 35](https://user-images.githubusercontent.com/839349/29151890-ae6c1f76-7db6-11e7-8052-18e7136f19fb.png)

Через поиск по репозиторию этой строки не находит 🤔

**Comment by ilyahoilik** [comment]
Спасибо, исправлю. Я также кнопку хотел переименовать. Ибо "Следующий" так себе, лучше сделать "Далее" или что-то типа того.
