### ISSUE TITLE
Уведомление - изменение репутации

### ISSUE THREAD

**Issue by cxemnet** [ilyahoilik/invision.system.ru#25]
notification__new_react | {!#[?:%s reacted to]} %s

Не работает вот эта конструкция:
{!#[1:%s отреагировал][?:%s отреагировали]} на %s

В окне уведомлений не отображается...

**Comment by ilyahoilik** [comment]
Да, я уже это видел. Вот так будет работать: `{!#[?:%s отреагировал]} на %s`. В следующей версии будет исправлено.
