### ISSUE TITLE
Галерея - Нет перевода в предупреждении

### ISSUE THREAD

**Issue by cv01** [ilyahoilik/invision.system.ru#28]
Предупреждение о том, что не добавлена информация ещё для N изображений.
![screenshot_20170828-124950](https://user-images.githubusercontent.com/30299222/29768901-aef19c3a-8bf0-11e7-93c3-139b91670d2c.png)

**Comment by ilyahoilik** [comment]
Даже не знаю почему она не отображается на русском. Вот эта строка https://github.com/ilyahoilik/invision.system.ru/blob/master/gallery.xml#L716

![2017-08-28-01-d3f14](https://user-images.githubusercontent.com/7265704/29782617-f372ca20-8c25-11e7-88df-cb007f18cd1f.png)

**Comment by cv01** [comment]
@ilyahoilik 
Строки переведены
![screenshot_20170828-193542](https://user-images.githubusercontent.com/30299222/29783223-3f9ea5fc-8c28-11e7-8a00-512eeabbbbcc.png)

**Comment by ilyahoilik** [comment]
@cv01 тогда не знаю. Версия системы последняя? Попробуй обнови перевод

**Comment by ilyahoilik** [comment]
Хотя обновление перевода не чистит кэш, запусти инструменты поддержки.

**Comment by cv01** [comment]
Очистка кеша помогла
![screenshot_20170829-105443](https://user-images.githubusercontent.com/30299222/29810591-126c25c4-8ca9-11e7-9121-2cff580684e9.png)
