### ISSUE TITLE
Галерея - не умещаются кнопки на мобильном

### ISSUE THREAD

**Issue by cv01** [ilyahoilik/invision.system.ru#29]
При загрузке изображений с мобильного кнопки не умещаются на строке.
![screenshot_20170828-124759](https://user-images.githubusercontent.com/30299222/29769041-361f13c2-8bf1-11e7-8cbd-ebbbccb3d3a2.png)
На английском всё ОК.
![screenshot_20170828-125521](https://user-images.githubusercontent.com/30299222/29769040-361ac52e-8bf1-11e7-9805-3c7493c8e7a6.png)

**Comment by cv01** [comment]
![](https://i.imgur.com/dNAqFsj.png)
@ilyahoilik Всё-равно не влезает

**Comment by ilyahoilik** [comment]
Пиши тогда в поддержку, пускай вёрстку исправляют
