### ISSUE TITLE
Галерея - не умещаются кнопки на мобильном (2)

### ISSUE THREAD

**Issue by cv01** [ilyahoilik/invision.system.ru#30]
На экране редактирования информации загруженных изображений не умещаются кнопки
![screenshot_20170828-124822](https://user-images.githubusercontent.com/30299222/29769099-85504ae2-8bf1-11e7-897c-0e7dd2febb8e.png)
На английском всё ОК:
![screenshot_20170828-125539](https://user-images.githubusercontent.com/30299222/29769098-8548b2be-8bf1-11e7-9094-b19ef607e5db.png)

**Comment by ilyahoilik** [comment]
Вот так это должно работать. На мобильном Chrome не заводится.

![2017-08-28-01-ebaef](https://user-images.githubusercontent.com/7265704/29782914-0c9ab264-8c27-11e7-8e3f-a2cf196cfadc.png)

**Comment by ilyahoilik** [comment]
Это не баг перевода :)
