### ISSUE TITLE
"Закрыто" о теме

### ISSUE THREAD

**Issue by chimit** [ilyahoilik/invision.system.ru#35]
Неясный перевод "Закрыто":

<img width="257" alt="2017-09-14 1 52 31" src="https://user-images.githubusercontent.com/839349/30392433-68d7ecde-98ef-11e7-87b1-7dd3dd0d09a7.png">
<img width="283" alt="2017-09-14 1 52 23" src="https://user-images.githubusercontent.com/839349/30392434-69088d1c-98ef-11e7-8795-ad6b2e7d99d9.png">

Наверно лучше подойдет "Закреплено" или "Зафиксировано".

**Comment by ilyahoilik** [comment]
Год назад писал им об этом, они сказали что не будут исправлять. Напишу ещё раз.

**Comment by ilyahoilik** [comment]
Посмотрел код и понял, что они даже сейчас это исправлять не будут. Ибо слишком сложно. Да и ни "Закреплено", ни "Зафиксировано" не подходит. Это слово отображается если язык установлен стандартным по всех областях - и в публичной части, и в Админцентре. Может "Закрыто" и не самый удачный вариант, но это не смертельно.
