### ISSUE TITLE
Не переведено "gallery_use_square_thumbnails"

### ISSUE THREAD

**Issue by chimit** [ilyahoilik/invision.system.ru#36]
<img width="633" alt="2017-09-14 1 56 05" src="https://user-images.githubusercontent.com/839349/30392609-ed267ad2-98ef-11e7-8aaf-0f7544672493.png">

**Comment by ilyahoilik** [comment]
Даже не знаю почему у вас это не переведено, у меня всё нормально. Да и в переводе это есть
https://github.com/ilyahoilik/invision.system.ru/blob/master/gallery.xml#L201

**Comment by chimit** [comment]
Буквально менее суток назад скачал перевод IPS 4.2.4 с ipshelp.ru. Странно.

**Comment by ilyahoilik** [comment]
И там он тоже есть. Попробуйте в поддержку написать, может помогут.
![2017-09-14-01-5feef](https://user-images.githubusercontent.com/7265704/30416709-e822935e-9935-11e7-96a8-5bd90b90d12a.png)

**Comment by ilyahoilik** [comment]
Закрываю так как не могу воспроизвести
