### ISSUE TITLE
Косяки в таблице лидеров

### ISSUE THREAD

**Issue by chimit** [ilyahoilik/invision.system.ru#38]
![2017-09-15 16 30 42](https://user-images.githubusercontent.com/839349/30473508-49317018-9a33-11e7-947a-f3036aa35101.png)

По обновлени**ям** статусов
По сообщения**м**
По записям в блогах
По изображения**м**
По альбом**ам**
По события**м** календаря

Ну и слово "Детали" немного неподходящее.

**Comment by ilyahoilik** [comment]
#61
