### ISSUE TITLE
Небольшая ошибка

### ISSUE THREAD

**Issue by Veratyr** [ilyahoilik/invision.system.ru#40]
В строке **notifications_user_count** сейчас присутствует формулировка "_Кому-то_", что приводит к уведомлениям вида "_Кому-то_ отреагировал на сообщение в теме". У себя исправил на "_кто-то_", предлагаю исправить и в репозитории, а также проверить не приводит ли к аналогичным эффектам строка **notifications_anonymous**

**Comment by ilyahoilik** [comment]
**Кому-то** понравилась запись. **Кто-то** отреагировал на сообщение. И в двух случаях используется одна и та же строка. Благо, это можно исправить, написав в поддержку. Это я и сделаю.

**Comment by ilyahoilik** [comment]
Проблема будет исправлена в одной из будущих версий (4.2.6 или 4.2.7):

> Thank you for bringing this issue to our attention. I have submitted a patch for the translation concern you raised which will be included in a future maintenance release.

**Comment by ilyahoilik** [comment]
В 4.2.6 поправили :)
