### ISSUE TITLE
Форма слова в уведомлении

### ISSUE THREAD

**Issue by Veratyr** [ilyahoilik/invision.system.ru#41]
Сейчас в строке __indefart_topic значение "тем**у**" приводит к уведомлениям вида "Юзернейм упомянул вас в тем**у**: Название". У себя заменил на "тем**е**", но не проверял используется ли эта подстановка и не ломает ли она другие формулировки. Стоит проверить и в случае необходимости исправить также в репо.

**Comment by ilyahoilik** [comment]
Используется, это единая языковая строка для многих областей сайта. Поэтому такие проблемы. Протестирую, если в основных областях лучше использовать `теме`, то исправлю.

**Comment by ilyahoilik** [comment]
Ломает, например в заголовках писем:
$member опубликовал **тему** (ожидает утверждения)

Это суперглобальная проблема практически со всеми строками, которые начинаются с `__defart` и `__indefart`. Решить её пока никак не получается, к сожалению. У меня для таких проблем есть даже отдельный статус, чтобы не потерять их из виду. Так что вешаю его. Может в следующих версиях системы они что-то изменят и тогда можно будет вернуться в этой проблеме.

**Comment by Veratyr** [comment]
В таком случае всё-равно пока лучше сделать "тем**е**", поскольку правильность формулировки в публичной часто встречающейся части всё же важнее, нежели в заголовках писем для ограниченного круга модераторов.

Проблема репортилась в IPS? Если есть линк, вообще было бы отлично.

**Comment by ilyahoilik** [comment]
В публичной части может и не репортилась. Я и ещё один человек с Германии, который также заинтересован в исправлении этих проблем, разговаривали с Марком по поводу этого. Он сказал, что проблему понял, но её решения у них по прежнему нет. Это было год назад. Не думаю, что сейчас что-то изменилось.

**Comment by ilyahoilik** [comment]
Иностранцам тяжело понять что нужно русскоязычным в плане языка. Тем, кто совершенно не знаком с русским языком, тяжело всё это представить и найти решение.

**Comment by Veratyr** [comment]
Да, много общался с IPS по вопросам, которых они стараются не касаться в силу того, что они не входят в круг их локальных потребностей, и порой они непрошибаемы в этом плане, даже если поняли суть проблемы. Но если долбить чаще и сильнее, то иногда сдаются. Например после долгой тикетной и e-mail войны всё же согласились реализовать поддержку oAuth 2.0 в будущих версиях(надеюсь не съедут с этих обещаний).
Здесь тот же случай. Думаю, что есть смысл зарепортить публично и сразу договориться с теми, кто в этом заинтересован, чтобы отписались и поддерживали активность в теме. Если широкая востребованность заметна, то всегда легче дать ход любой проблеме, чем если к её решению проявляет интерес всего несколько человек.

**Comment by ilyahoilik** [comment]
Нашёл ссылку на баг-репорт по поводу похожей проблемы. Но они закрыли баг-трекер, поэтому сейчас уже ничего не посмотришь.

#61
