### ISSUE TITLE
Слитная каша в описании кастомных потоков активности

### ISSUE THREAD

**Issue by Veratyr** [ilyahoilik/invision.system.ru#42]
Если в потоке активности настроить кастомную фильтрацию, описание отображается слитно без пробелов и запятых между подстановками. В английском варианте всё ок.

Чтобы быть точнее, речь о том, что выводится в `<span data-role='streamBlurb'>{$stream->blurb()}</span>`

**Comment by ilyahoilik** [comment]
Можете привести скриншот настроек потока? Не могу воспроизвести.

**Comment by Veratyr** [comment]
![bug](https://user-images.githubusercontent.com/2811248/30779390-09d5d546-a0f8-11e7-84a2-43d59c547405.png)

**Comment by Veratyr** [comment]
Аналогичная проблема наблюдается в уведомлениях с перечислением ников:
![bug2](https://user-images.githubusercontent.com/2811248/30779595-827c2c34-a0fd-11e7-9647-4c3638cf2268.png)

Пояснение к скриншоту: GPCracker и ЛОМ — это разные никнеймы, а не один.

В целом по интерфейсу похоже проблема касается именно локализованных _перечислений_.

**Comment by ilyahoilik** [comment]
Всё равно не могу воспроизвести. За запятые отвечает строка  `_list_format_`. Просмотрите как она у вас в системе переведена? Должно быть `a, b и c`, как и здесь - https://github.com/ilyahoilik/invision.system.ru/blob/master/core.xml#L613.

**Comment by Veratyr** [comment]
Странно. Именно так и есть, всё совпадает. После пересохранения строки ровно с тем же значением проблема исправилась. В общем, редкий глюк и частный случай. Не баг перевода.
