### ISSUE TITLE
Keys forums & menu__forums_forums_forums

### ISSUE THREAD

**Issue by Veratyr** [ilyahoilik/invision.system.ru#43]
Сейчас по ключам forums и menu__forums_forums_forums используется строка "Категории и разделы". Не знаю, сложилось ли это исторически, или просто ошибка, но у себя перевёл как "Форумы". Смотрится лучше, воспринимается легче. Рекомендую сделать также в репо.

**Comment by Veratyr** [comment]
Также стоит обратить внимание на r__forums_add, r__forums_delete, r__forums_edit, r__forums_manage

**Comment by ilyahoilik** [comment]
> Не знаю, сложилось ли это исторически, или просто ошибка
Исторически. В переводе **Форум** (в единственном числе) - это глобальный раздел сайта, отдельное приложение. А частями этого форума являются категории, внутри которых находятся разделы.

Я оставлю этот репорт как предложение по улучшению русификации, возможно что-нибудь переделаем именно в этих строках. Например, menu__forums_forums_forums переведём как **Форум**, ведь оно отображается на главной странице приложения. А в r__forums_* сделаем **Может создавать/изменять/... разделы форума**. В общем подумаем.

**Comment by ilyahoilik** [comment]
Так как у нас **Форум** - это приложение/раздел сайта, его частями являются категории и разделы, и в вышеупомянутых строках никаких несоответствий нет, то репорт закрываю.
