### ISSUE TITLE
Опечатка и формулировки

### ISSUE THREAD

**Issue by Veratyr** [ilyahoilik/invision.system.ru#44]
В строках no_module_permission, no_module_permission_admin и no_module_permission_guest есть опечатка: "Страница, к котор**ы**й" (правильно: "к котор**о**й").

Также здесь уместно изменить формулировку для сокращения и упрощения текста, т.к. дословый перевод довольно недружелюбен и с тавтологией.

У себя сделал так: 

`no_module_permission`
> Эта страница недоступна для вашего аккаунта.

`no_module_permission_admin`
> Эта страница недоступна для вашего аккаунта. Для настройки прав доступа к приложениям перейдите в Админцентр → Система → Приложения.

`no_module_permission_guest`
> Эта страница недоступна для гостей, но, возможно, доступна для зарегистрированных пользователей.

**Comment by ilyahoilik** [comment]
Спасибо, исправлю.

**Comment by ilyahoilik** [comment]
Как думаете, если вместо `Эта` поставить `Запрашиваемая`, то будет нормально? Или лучше `Эта`?

**Comment by Veratyr** [comment]
Я склоняюсь к тому, что с юзером лучше общаться всегда на максимально простом и понятном языке. "Эта" — лучше с такой позиции. Запрос — технический термин, далеко не каждый юзер отдаёт себе отчёт в том, что он не просто "открывает" страницы, а делает запрос.

**Comment by ilyahoilik** [comment]
Closed by #55
