### ISSUE TITLE
Словоформа

### ISSUE THREAD

**Issue by Veratyr** [ilyahoilik/invision.system.ru#45]
Ещё [вот такую](https://koreanrandom.com/forum/uploads/monthly_2017_09/2017-09-24_14-59-08.png.cd4e6dfde93fa06f2e9b68c6a74962d0.png) мелочь репортили. Не критично, но можно поправить (должно быть 313 сообщени**й**).

**Comment by ilyahoilik** [comment]
Буду тестировать, похоже нужно добавить ещё четыре значения - для строк, оканчивающихся на *11, *12, *13, *14. Если да, то это глобальный баг и мне придётся слишком много править. Отложу на 4.2.6.

**Comment by ilyahoilik** [comment]
Да, это глобальный баг. Исправил сразу во всех строках с помощью замены по регулярному выражению.
