### ISSUE TITLE
edited_lc

### ISSUE THREAD

**Issue by Veratyr** [ilyahoilik/invision.system.ru#58]
В строке edited_lc слово "edited" переведено как "Изменено", однако в контексте его использования уместнее использовать "Редактировалось".

Дело в том, что строка используется сразу после даты публикации сообщения, а текущая формулировка вводит в заблуждение, поскольку рядом с датой может показаться, что дата означает не публикацию, а время редактирования. Слово "Редактировалось" более нейтрально и не меняет восприятие, оставаясь простым указателем на то, что сообщение было изменено, как и было задумано IPS.

**Comment by ilyahoilik** [comment]
Спорное изменение, если честно.

У нас в большинстве используется именно "Изменить", а не "Редактировать". Соответственно, сообщение было "Изменено", а не "Редактировано". Это простое приведение терминов к единому стилю. Я пока не понимаю чем отличается "Изменено" от "Редактировалось", ведь можно также понять эту строку как "<время публикации> редактировалось". То есть проблема никуда не исчезнет.

Гляну чуть позже как это в живую выглядит.

**Comment by ilyahoilik** [comment]
Посмотрел. В принципе я согласен, что `(изменено)` можно отнести к дате, а не к самой публикации. Но изменение этой строки на `редактировалось` совершенно ничего не изменит, а лишь внесёт несоответствие с названием функции "Изменить". Есть ещё вариант написать `изменялось`, но и он тоже ничего не изменит.

**Comment by ilyahoilik** [comment]
Кстати, к английском тоже можно неверно интерпретировать эту строку. Для исправления этой проблемы конечно лучшим вариантом было бы добавить дату, вот таким образом:

> Опубликовано: 18 июля (изменено 15 октября)

Но я сомневаюсь, что это когда-нибудь сделают.
