### ISSUE TITLE
"Перейти к комментарий" при рекомендации сообщения в теме

### ISSUE THREAD

**Issue by cv01** [ilyahoilik/invision.system.ru#6]
![screen_2017-07-21_14-15-42_010](https://user-images.githubusercontent.com/30299222/28461454-5080b198-6e1f-11e7-81fd-f542bbfaf317.jpg)
"Перейти к **комментарий**"
Всё как обычно в IPS :)

**Comment by ilyahoilik** [comment]
Я разве что "к" могу заменить на "в". Но тогда всё равно где-то станет неправильно. Потом насобираю все поожие случаи и одним тикетом отправлю в Invision.

**Comment by ilyahoilik** [comment]
#61
