### ISSUE TITLE
content_record_actions

### ISSUE THREAD

**Issue by Rammoff** [ilyahoilik/invision.system.ru#60]
Ключ: content_record_actions
Английский перевод: %s actions
Ваш перевод: Изменить
Мое предложение: Действия

![screenshot_2](https://user-images.githubusercontent.com/30965384/31577351-643fb0ce-b115-11e7-83b4-c8c512b1240e.png)
![screenshot_1](https://user-images.githubusercontent.com/30965384/31577359-8a48c850-b115-11e7-9b42-1c3f16d0190d.png)

**Comment by Sipsb** [comment]
Мне кажется (Изменить) более понятный перевод.

**Comment by Veratyr** [comment]
Sipsb, ссылка "изменить" уже есть в этой строке, и находится прямо рядом с кнопкой, которую предлагается переименовать. Два элемента с одинаковыми названиями и разными эффектами - однозначно "более понятный" вариант в конечном счёте.

**Comment by ilyahoilik** [comment]
Да, я согласен что не должно быть две одинаковые кнопки рядом. Если есть вариант лучше, чем `Действия`, то предлагайте. Но так как речь идёт именно о действиях над публикацией (закрепить, рекомендовать, закрыть и так далее), то мне кажется это неплохой вариант.

**Comment by Veratyr** [comment]
Вариант "Действия" вполне подходящий.

**Comment by Rammoff** [comment]
Еще добавлю: file_actions
Тоже перевод также следовало бы поменять.

**Comment by ilyahoilik** [comment]
Спасибо, `file_actions` тоже исправил
