### ISSUE TITLE
activity_member_reacted

### ISSUE THREAD

**Issue by Rammoff** [ilyahoilik/invision.system.ru#63]
Похоже что во время перевода все стояло на локалке, а вот ссылки неисправны.
![screenshot_3](https://user-images.githubusercontent.com/30965384/31663090-89e63560-b349-11e7-919d-c8ccbf149310.png)
![screenshot_4](https://user-images.githubusercontent.com/30965384/31663100-951c7bc4-b349-11e7-90e7-6247da197e75.png)

**Comment by ilyahoilik** [comment]
Закрыто как дубликат #57
