### ISSUE TITLE
Отсутствует перевод для строки topic_content

### ISSUE THREAD

**Issue by vinegredz** [ilyahoilik/invision.system.ru#77]
Эта строка используется в качестве label для всех полей типа Редактор.

**Comment by ilyahoilik** [comment]
Данная строка пустая, соответственно переводить нечего

**Comment by vinegredz** [comment]
Это не пустая строка, а баг. Так как на сайте остается только подпись "обязательно", а label пустой. Если указать перевод, то строка языковая будет отображаться в редакторе.

**Comment by ilyahoilik** [comment]
Есть факт - строка пустая, то есть переводить нечего. Если вы считаете, что там должен быть какой-то текст, то [сообщите разработчикам](https://invisioncommunity.com/clientarea/support/create/) и как только в строке появится текст, который я смогу перевести, я сделаю это.
