### ISSUE TITLE
Можно сократить фразу "Уже зарегистрированы? Войти" не теряя смысл

### ISSUE THREAD

**Issue by vinegredz** [ilyahoilik/invision.system.ru#78]
На мой взгляд ничего не изменится если оставить просто "Вход" или "Вход на сайт"

**Comment by ilyahoilik** [comment]
Ну как ничего не изменится? Строка станет короче и по ней станет труднее попасть (шутка :laughing:). Можно конечно изменить на "Вход на сайт" или "Войти на сайт". Нужно обсуждать.

@chimit, @Sipsb, что скажете?

**Comment by chimit** [comment]
На мой взгляд, строчка не намного длиннее оригинальной, интерфейс не портит. Особым чайникам (а у меня такие есть) она может облегчить жизнь.

**Comment by Sipsb** [comment]
"Вход на сайт" звучит неплохо, если посмотреть на другие сайты, магазины и.т. большинство использует как "Войти".

**Comment by Takohashi** [comment]
«Вход на сайт» звучит плохо, потому что это вход не на сайт, а на форум.

**Comment by vinegredz** [comment]
IPB давно не про форумы. Тем более что фраза глобальная, отображается на всех страницах в том числе и в разделах с файлами, блогах и т.д.

**Comment by Takohashi** [comment]
Если у Вас не про форумы, тогда вы можете самостоятельно открыть в админке правку локализации и изменить текст на подходящий лично Вам.

**Comment by Sipsb** [comment]
> «Вход на сайт» звучит плохо
> 
Тогда просто "Войти"

![2017-11-21_14-22-53](https://user-images.githubusercontent.com/22107941/33070022-9c06cffe-cec7-11e7-855f-b58a318a6576.png)

**Comment by ilyahoilik** [comment]
Лично моё мнение - сейчас перевод самый точный из всех возможных и, если он не вписывается в чей-то дизайн, то эту строку легко можно изменить самостоятельно. К тому же вопрос `Уже зарегистрированы?` действительно носит смысловой характер.
