### ISSUE TITLE
Имена email-шаблонов

### ISSUE THREAD

**Issue by chimit** [ilyahoilik/invision.system.ru#81]
Наткнулся на непереведенное имя email-шаблона:

![2017-11-22 14 09 00](https://user-images.githubusercontent.com/839349/33112554-d38f5118-cf8e-11e7-9bdf-63578df6da49.png)

Языковой строчки `emailtpl_notification_new_react` не нашел.

**Comment by Sipsb** [comment]
Надо писать в **bug tracker**, для теста переустановил IPS проблема остаётся по дефолту.

**Comment by ilyahoilik** [comment]
Исправлено в 4.3.0
