### ISSUE TITLE
«1-ый, 2-ой, 3-ий» в таблице лидеров

### ISSUE THREAD

**Issue by Takohashi** [ilyahoilik/invision.system.ru#84]
Есть небольшое предложение — в таблице лидеров изменить **1-ый, 2-ой, 3-ий** на **1-е, 2-е, 3-е**

1. Текущий вариант по сути некорректен, поскольку согласно правилам русского языка двухбуквенные наращения используются только для -го, -му, -ми. В остальных случаях используется наращение из одной буквы. http://new.gramota.ru/spravka/letters/87-rubric-99
2. Предложенный вариант по смыслу привязывается к слову **место** (1-е место и тд).

**Comment by ilyahoilik** [comment]
Спасибо, ваш вариант действительно лучше
