### ISSUE TITLE
 Пользователи, поставившие реакцию

### ISSUE THREAD

**Issue by Takohashi** [ilyahoilik/invision.system.ru#85]
Перепощу сюда с форума. При добавленных реакциях к сообщению выводится только надпись «Вы отреагировали на это». Другие пользователи не указываются.

Английский:
![2017-12-25 8 33 02](https://user-images.githubusercontent.com/9580166/34334666-66f80d4e-e959-11e7-9cf5-7a4108a64471.png)
Русский:
![2017-12-25 8 35 19](https://user-images.githubusercontent.com/9580166/34334669-6fc13ca2-e959-11e7-89ed-0dec563e129f.png)

Чтобы исправить этот баг, замените в ключе **react_blurb** это:
`%s {!# [1:%s отреагировал][?:%s отреагировали]} на это`
на это:
`%s {!# [1:отреагировал][?:отреагировали]} на это`

**Comment by ilyahoilik** [comment]
Спасибо, теперь понял
