### ISSUE TITLE
Сообщение об отправленном письме при регистрации

### ISSUE THREAD

**Issue by Takohashi** [ilyahoilik/invision.system.ru#86]
Ключ: **validation_email_rate_limit**

Первое предложение из оригинала:
The email was sent to you %s.

Текущий перевод:
Письмо было отправлено вам на %s.

Я так понимаю, что под %s подставляется не адрес почты, а дата/время отправки, потому что сейчас в журнале ошибок увидел следующее — «Письмо было отправлено вам на только что.»
Если так, то из перевода надо убрать предлог «на».

**Comment by ilyahoilik** [comment]
Спасибо! :+1:
