### ISSUE TITLE
"Staff Directory"

### ISSUE THREAD

**Issue by Veratyr** [ilyahoilik/invision.system.ru#89]
Сейчас "Staff Directory" переведено как "Список администрации", что не совсем верно, а в некоторых случаях даже совсем неверно из-за замены понятия персонала на администрацию.
Особенно если на форуме всего один администратор, но в то же время есть большая команда модераторов и иного персонала.

Думаю, что будет лучше, если перевести дословно, либо более обобщённо, без упоминания конкретных позиций, например: "Список персонала" или "Команда форума", "Наша команда" или даже просто "Команда".

**Comment by ilyahoilik** [comment]
Под администрацией я как раз понимал всех, кто работает над сайтом. То есть администрация делится на администраторов и модераторов. Из предложенных вариантов мне кажется, что хорошо читается только `Команда форума`, хотя и тут стоить заменить `форума` на `сайта`. Надо думать.

**Comment by Sipsb** [comment]
По мне "Команда форума" звучит хорошо, а вот  "Команда сайта" не подойдёт, если форум установлен как дополнение к основному сайту.

**Comment by ilyahoilik** [comment]
А если форум не установлен/не используется?

**Comment by Sipsb** [comment]
Хмм.. надо подумать.

**Comment by FoLez** [comment]
**Наши сотрудники**, как вам такой вариант?

**Comment by Veratyr** [comment]
Сотрудники - не универсально. На большинстве известных мне форумов модераторами являются не сотрудники, и не администрация, а волонтёры. В этом случае формулировка будет вводить в заблуждение также, как и текущая. На данный момент варианты  "Команда" или "Наша команда" видятся оптимальными, т.к. не привязываются ни к позиции перечисленных пользователей в проекте, ни к используемым приложениям (сайт/форум).

**Comment by ilyahoilik** [comment]
Не понимаю почему люди считают, что форум не является сайтом. Ведь форум это лишь его часть. В Админцентре на самом видном месте находится кнопка `Перейти на сайт`. И даже сейчас можно в публичной части найти строки, где глобальное понятие - именно `сайт`.

`Сотрудники` - точно нет. `Наша команда` - не хотелось бы включать местоимение в заголовок страницы, тем более как его первое слово. Но слово `Команда` действительно в точку, оно подойдёт и для игровых сайтов, и для каких-то корпоративных. Пока склоняюсь к `Команда сайта`, но ещё подумаю.

**Comment by Takohashi** [comment]
Форум — это самодостаточная часть сайта, зачастую имеющая даже совершенно другое оформление. Не знаю, зачем смешивать эти понятия. На западе понятно — там «сайтом» называют всё подряд, а под «форумом» там как правило понимаются сами обсуждения (или разделы тем).
Под «командой сайта» я понимаю людей, которые занимаются развитием сайта — от дизайна до наполнения контентом. А «команда форума» — это просто обслуживающий персонал в виде модераторов, и этот вариант ближе. «Наша команда» — самый оптимальный и нейтральный вариант.

**Comment by ilyahoilik** [comment]
У меня большие вопросы только к местоимению `наша`. Я сделал такой перевод на тестовом сайте и при нахождении на обсуждаемой странице сразу возникает вопрос: `наша` - это чья? Особенно если поместить это в меню, тогда не знакомый с ситуацией человек вообще может трактовать неверно этот пункт.

`Наша` хорошо звучит при общении между собой администраторов. А вот когда мы даём это читать пользователю (именно не говорим ему сами, а даём читать), то привязка этого местоимения к кому-либо теряется.

Так что я за то, чтобы если и изменять данный термин (`Staff Directory`), то новая версия должна быть чёткая и пользователь не должен заходить на страницу, чтобы понять что там находится.

**Comment by Takohashi** [comment]
Ну, меню «Наш выбор» же никого не смущает...

**Comment by ilyahoilik** [comment]
Подумаю. Мне вариант `Наша команда` совершенно не нравится, но если всем остальным он нравится и все так против `Команды сайта`, то значит я ошибаюсь. Правда стоит ещё раз вернуться к `Списку администрации` и решить хуже он `Нашей команды` или нет.

**Comment by ilyahoilik** [comment]
/polls "Список администрации" "Наша команда" "Команда сайта" "Все варианты так себе"

**Comment by Takohashi** [comment]
Я не против и команды, но не сайта, а форума. Не понимаю, зачем форум называть сайтом.

**Comment by ilyahoilik** [comment]
Эта страница никак к форуму не относится, она именно про администраторов/модераторов на всем сайте. То есть на ней можно создать категорию "Модераторы блога" и туда закинуть модераторов, которые занимаются только блогом. Именно поэтому я и против именования `Команда форума`. Ну ещё и потому, что на некоторых сайтах форума может просто не быть. Например, только магазин.

**Comment by Takohashi** [comment]
А можно какие-нибудь примеры **не** форумов на Инвижине?

Ну тогда уж просто «Персонал» и «Список персонала» и не ломать голову.
