### ISSUE TITLE
Поля регистрации

### ISSUE THREAD

**Issue by Sipsb** [ilyahoilik/invision.system.ru#90]
Предлагаю изменить поля регистрации на форуме:

- Имя пользователя —> **Придумайте имя пользователя или  Придумайте логин**
- Email-адрес —> **Введите свой Email-адрес**
- Пароль —> **Придумайте пароль**
- Подтвердить пароль —> **Повторите пароль**

Выбор пароля  —> **Надежность пароля это важно!**. Мы же его не выбираем а придумываем.

Рекомендуемая длина пароля —> **Рекомендации по вводу пароля**

- 8 или более символов
- Смеси буков и цифр  —> **Смесь буков и цифр**
- Смеси прописных и строчных букв  —> **Смесь прописных и строчных букв**
- Специальных символов  —> **Используйте специальные символы**
- Ненастоящих слов  —> **Придумайте что-то своё**

Так же и сами статусы ввода пароля

- Очень слабый —> **Слишком короткий**
- Слабый —> **Относительно надежный**
- Хороший  —> **Вполне надежный**
- Сильный —> **Надежный**

В общем как-то так.
![2018-01-22_14-27-09](https://user-images.githubusercontent.com/22107941/35227623-9ec3c270-ff9f-11e7-84a5-efcfb18db1aa.png)

**Comment by Takohashi** [comment]
Это как-то изменения ради изменений.
Вот, что точно нужно исправить — это «буков» на «букв».

**Comment by Sipsb** [comment]
Да поправил уже. 
На одном форуме луди преклонного возраста, постоянно парятся и спрашивают чьё имя вводить и Email-адрес, что Email-адрес? Регистрировать или же вводить свой. Думаю, не лишним будет конкретизировать вопросы.

**Comment by ilyahoilik** [comment]
Только с некоторыми моментами согласен, позже распишу

**Comment by ilyahoilik** [comment]
В большинстве предложенных изменений не вижу особого смысла.

Заменил "Подтвердить" на "Повторите" в поле пароля. В окошке с рекомендациями по паролю сделал несколько изменений. Но полностью перечеркивать первоначальный смысл фраз (как с предложенным "Придумайте что-то своё") мы точно не будем.

Я могу подкрутить что-то, если мой перевод оказался многим непонятен. Но крутить просто потому, что на каком-то форуме кто-то что-то не понял - это не ко мне. Тем более данные строки довольно очевидные.

На GitHub есть замечательная возможность - форкайте репозиторий, вносите необходимые вам изменения и у вас появляется перевод, который нужен именно вам. И обновлять его очень легко, для этого я и сделал всё именно таким образом.

**Comment by ilyahoilik** [comment]
<img width="991" alt="2018-02-08 0 12 37" src="https://user-images.githubusercontent.com/7265704/35943290-950dd898-0c69-11e8-951a-70dfc1ae3a9e.png">
