### ISSUE TITLE
Багрепорты по форуму

### ISSUE THREAD

**Issue by serhero** [ilyahoilik/invision.system.ru#91]
![2018-02-05 3](https://user-images.githubusercontent.com/36163951/35812908-48ca2328-0aa3-11e8-9fa4-9ad092384a46.jpg)
Здесь напрашивается:
SerGEAnt ответил в теме, созданной пользователем SerGEAnt в разделе "О нашем портале".

Ну и опечатки:

![fb714d43904a24f12e48eaf837bba8c3](https://user-images.githubusercontent.com/36163951/35812910-48f14f2a-0aa3-11e8-8a9a-478069662289.png)

![58d522cf](https://user-images.githubusercontent.com/36163951/35812911-495d7a10-0aa3-11e8-9c80-b303d7712e0d.jpg)

**Comment by Takohashi** [comment]
Первый скрин из ленты активности? У меня там написано «_Ник_ ответил в тему пользователя _Ник_ в _Название_»

**Comment by ilyahoilik** [comment]
В нашей русификации таких проблем нет

**Comment by ilyahoilik** [comment]
Разобрались, я в теме на форуме отписался
