### ISSUE TITLE
Окно пересчёта публикаций / репутации

### ISSUE THREAD

**Issue by Takohashi** [ilyahoilik/invision.system.ru#95]
1. Сейчас в окне пересчёта публикаций / репутации кнопки не влезают на одну строку:

![2018-02-21 2 52 48](https://user-images.githubusercontent.com/9580166/36455826-fc1e94ac-16b2-11e8-85ba-5e82ce03d8d2.png)

Может быть стоит перевести кнопку как «Пересчитать для всех»?:

![2018-02-21 2 53 12](https://user-images.githubusercontent.com/9580166/36455840-12750d9e-16b3-11e8-91fe-319d6914caf1.png)

2. Также в окне пересчёта публикаций стоит исправить «Это действие пересчитает количество публикаций пользовател**ей**» на «Это действие пересчитает количество публикаций пользовател**я**».

3. А в окне пересчёта репутации исправить «Это пересчитает текущий уровень репутации пользователя» на «Это **действие** пересчитает текущий уровень репутации пользователя».

**Comment by ilyahoilik** [comment]
Обожаю такие подробные баг-репорты, спасибо
