### ISSUE TITLE
Заголовок цитаты

### ISSUE THREAD

**Issue by Takohashi** [ilyahoilik/invision.system.ru#96]
Сейчас заголовок цитаты имеет следующий вид:
"В 09.02.2018 в 12:32, Ник сказал:"
Есть ли возможность убрать самую первую «В», которая там не нужна?

Да и запятая в общем тоже не нужна.

**Comment by ilyahoilik** [comment]
В строке `time_other` удалил "В ", надеюсь это не приведет к проблемам

**Comment by Takohashi** [comment]
В time_other всё ещё присутствует «В» :/
