### ISSUE TITLE
Косяки в ACP в Таблице лидеров

### ISSUE THREAD

**Issue by chimit** [ilyahoilik/invision.system.ru#97]
![2018-03-02 14 53 01](https://user-images.githubusercontent.com/839349/36886885-7916ec7a-1e29-11e8-94bb-4b5633307963.png)

Косяки с падежами:

1. По обновления статусов
2. По сообщения
3. По записи блога
4. По изображения
5. По альбомы
6. По события календаря

Кстати, чем отличаются "По сообщениям" и "По публикациям"? Публикации - это любые публикации, а сообщения - это только форумные? Но у меня сообщений больше, чем публикаций.

**Comment by Takohashi** [comment]
> Косяки с падежами
По этому вопросу уже был тикет — https://github.com/ilyahoilik/invision.system.ru/issues/38 В тикете #61 разъяснение на этот счёт.

> Публикации - это любые публикации, а сообщения - это только форумные? Но у меня сообщений больше, чем публикаций.
Да, сообщения — форумные, публикации — включая другое содержимое. Если у вас кол-во сообщений больше кол-ва публикаций, то вероятно, что у вас в настройках каких-то разделов отключено увеличение счётчика.

Единственное — по-моему ключ **member_post_count** неправильно переведён. Создал тикет по этому поводу — https://github.com/ilyahoilik/invision.system.ru/issues/98
