### ISSUE TITLE
Перевод member_post_count

### ISSUE THREAD

**Issue by Takohashi** [ilyahoilik/invision.system.ru#98]
Мне кажется, что ключ **member_post_count** неправильно переведён. Переведено как «публикации», а должно быть «сообщения» — в постах под аватарами сейчас выводится «X публикаций», а должно быть «Х сообщений» (в оригинале «X posts»).

**Comment by ilyahoilik** [comment]
Там именно публикации, не только форумные. Я создал новый файл в одноименном приложении и счетчик публикаций увеличился. С статьями в блогах также.

**Comment by Takohashi** [comment]
Да, точно... Сам вчера запутался и, когда проверял, не на те данные посмотрел.
